"""Fresh migration

Revision ID: e7cf814d081f
Revises: 3ea71ce71e00
Create Date: 2025-08-18 13:08:40.150916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cf814d081f'
down_revision: Union[str, Sequence[str], None] = '3ea71ce71e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('company_overview', sa.Text(), nullable=True),
    sa.Column('business_activities', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('group_companies', sa.Text(), nullable=True),
    sa.Column('major_business_partners', sa.Text(), nullable=True),
    sa.Column('sales_trends', sa.Text(), nullable=True),
    sa.Column('president_message', sa.Text(), nullable=True),
    sa.Column('interview_articles', sa.Text(), nullable=True),
    sa.Column('past_transactions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('career_history', sa.Text(), nullable=True),
    sa.Column('current_activities', sa.Text(), nullable=True),
    sa.Column('publications', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    op.drop_table('organizations')
    # ### end Alembic commands ###
